# -*- coding: utf-8 -*-
"""scratchfile.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fzD6cVME4T3bxLMGmUg2C8BRh_QrKyFO
"""

import pandas as pd
import numpy as np
import time

import streamlit as st
st.title('STREAMLIT APP DEPLOYMENT')
st.write('Welcome, *Everyone!* :sunglasses:')

